name: "auto-tagging"

on:
  schedule:
    # Test: run every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and Push Tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d')"
          git tag -a $TAG_NAME -m "Continuous release $TAG_NAME"
          git push origin $TAG_NAME
