name: Fast Auto Tag and Release (Testing)

on:
  workflow_dispatch:
  schedule:
    - cron: "45 1 * * *"
    - cron: "15 9 * * *"
    - cron: "30 17 * * *"

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Increment version and update file
        run: |
          # Extract the current version from configure.ac
          VERSION=$(grep -o 'next-[0-9]\+\.[0-9]\+' configure.ac | head -n 1 | sed 's/next-//')
          echo "Current version: $VERSION"
          TAG="v$VERSION"
          # Increment the minor version
          IFS='.' read -ra version_parts <<< "$VERSION"
          MAJOR="${version_parts[0]}"
          MINOR="${version_parts[1]}"
          NEXT_VERSION="$MAJOR.$((MINOR+1))"

          # Write back to file
          sed -i "/AC_INIT(\[tmux\], next-$CURRENT_VERSION)/s/next-$CURRENT_VERSION/next-$NEXT_VERSION/" configure.ac

          # Set environment variable to use in subsequent steps
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Config git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create tag
        run: |
          git tag -a "v$TAG" -m "Release $TAG"
          git push origin "$TAG"
          git push

      - name: Commit changes
        run: |
          git add configure.ac
          git commit -m "Increment version to $NEXT_VERSION"

        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: update-tag
    runs-on: "ubuntu-latest"
    # env:
    #   JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0

      - id: "yarn-cache"
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: "actions/cache@v2.1.6"
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      # - run: "yarn install --frozen-lockfile"
      # - run: "yarn lint"
      # - run: "yarn build"
      # - run: "yarn jest --env=node --colors --forceExit"

      # - run: "sh autogen.sh"
      # - run: "./configure"
      - run: "sudo apt-get update -qq"
      - run: "sudo apt-get -y install bison \
          autotools-dev \
          libncurses5-dev \
          libevent-dev \
          pkg-config \
          libutempter-dev \
          build-essential"
      - run: "sh .github/travis/before-install.sh"
      - run: "sh .github/travis/build.sh"
      - run: "make dist"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            *.tar.gz
        id: "automatic_releases"

      # marvinpinto/action-keybase-notifications
      # marvinpinto/action-automatic-releases
      # - name: "Automatically mirror release artifacts"
      #   env:
      #     GITHUB_SUPER_TOKEN: ${{ secrets.GITHUB_SUPER_TOKEN }}
      #   run: |
      #     ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"

      # - uses: "marvinpinto/action-keybase-notifications@latest"
      #   if: always()
      #   with:
      #     job_status: ${{ job.status }}
      #     opensentinel_token: ${{ secrets.OSL_TOKEN }}
