name: CI Test Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v2

      - name: Set up compiler
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            echo "GCC setup placeholder"
          elif [ "${{ matrix.compiler }}" == "clang" ]; then
            echo "Clang setup placeholder"
          fi
        shell: bash

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Check compiler version
        run: ${{ matrix.compiler }} --version
